const LINKS={github:"https://github.com/ycoj2309",linkedin:"https://www.linkedin.com/in/jahdiel-k",email:"jkinvi@eugeniaschool.com",nbaRepo:"https://github.com/ycoj2309/project-nba-scraping",olistTableau:"https://public.tableau.com/app/profile/jahdiel.kinvi/viz/Business_Case_Olist/DashboardOlist",payfitLive:"https://payfit-pied.vercel.app/",notion:"https://www.notion.so/Dernier-Rendu-50ea37a3ed7c4dd3b995a5a000fb3d94",linkedinPost:"https://www.linkedin.com/feed/update/urn:li:activity:7420737202772512768/",miraklGh1:"https://github.com/ycoj2309/hackathon-mirakl",miraklGh2:"https://github.com/noahsgds/mirakl/tree/claude/mirakl-campaign-dashboard-qCmaU/scripts",miraklLoom1:"https://www.loom.com/share/cd1f2735f28345b1969133164d1bd1eb",miraklLoom2:"https://www.loom.com/share/bcab44d3cdbf46b69778a7dc74e1843f",miraklVercel:"https://mirakl.vercel.app/"};

const T={fr:{
"nav.projects":"Modules","nav.skills":"Skills","nav.certs":"Certifications","nav.contact":"Contact",
"portal.kicker":"STATION COGNITIVE ORBITALE","portal.sub":"Centre de recherche orbital dédié à l'Intelligence Artificielle et à la Data Science appliquée au Business","portal.cta":"[ CLIQUEZ POUR ENTRER ]","portal.b1":"Research Nodes",
"transition.1":"Scan biométrique en cours...","transition.2":"Accès autorisé","transition.3":"Ouverture du noyau cognitif",
"cabin.prompt":"Cliquez pour activer le scan cognitif","corridor.left":"Restricted Access","corridor.right":"Module Offline",
"globe.label":"NOYAU COGNITIF CENTRAL",
"projects.kicker":"MODULES DE RECHERCHE","projects.title":"Archives de la station cognitive","projects.desc":"Chaque module représente un projet réel, documenté et opérationnel.",
"skills.kicker":"CONSOLE COGNITIVE","skills.title":"Skill Matrix — Cartographie des compétences",
"certs.kicker":"ACCRÉDITATIONS","certs.title":"Certifications, Diplômes & Distinctions",
"contact.kicker":"CANAL DE COMMUNICATION","contact.title":"Prêt à collaborer sur des projets Data & IA","contact.cvTitle":"Curriculum Vitae",
"footer.text":"Construit avec passion pour la Data, l'IA et le Business",
"bot.status":"base locale","bot.chipProjects":"Projets","bot.chipSkills":"Skills","bot.chipContact":"Contact","bot.placeholder":"Question sur mon profil...","bot.send":"Envoyer",
"bot.welcome":"Bienvenue dans la KCSS. Posez vos questions sur mes projets, compétences ou parcours.",
"bot.projects":"Les 6 modules : Mirakl Nexus (IA agentique), PayFit Content Engine (SEO IA), Safran GMAO (industrie), TodoMaking (agent Dust), Olist Dashboard (BI Tableau), NBA Analytics (scraping Python).",
"bot.skills":"Compétences en IA/agentique (Dust, n8n, Make), Data (Python, SQL, Power BI, Tableau), Dev (HTML/CSS/JS, GitHub), Méthodes (PMO, AMDEC, 5S).",
"bot.contact":"Email: jkinvi@eugeniaschool.com | LinkedIn: linkedin.com/in/jahdiel-k | GitHub: github.com/ycoj2309",
"bot.default":"Je n'ai pas cette info précise. Demandez-moi sur les projets, skills ou contact.",
"filter.all":"Tout","filter.ai":"IA","filter.data":"Data","filter.business":"Business","filter.industry":"Industrie",
"card.open":"Explorer","card.github":"GitHub",
"modal.context":"Contexte","modal.objective":"Objectif","modal.result":"Résultats","modal.stack":"Stack","modal.links":"Liens",
"profile.scan":"[Holographic Scan Active]","profile.identity":"IDENTITÉ","profile.role":"RÔLE","profile.org":"ORGANISATION","profile.edu":"FORMATION","profile.status":"STATUT",
"profile.roleVal":"Data Analyst & Coordinateur de Projets","profile.orgVal":"PMU — Développement Réseau Commercial","profile.eduVal":"Eugenia School — MSc AI Applied to Business","profile.statusVal":"Active Cognitive Node — Kinvi Cognitive Space Station",
"profile.summary":"Spécialisé dans les systèmes décisionnels data-driven et l'IA appliquée aux opérations business. Contribue actuellement à l'optimisation du réseau commercial PMU. Construit des frameworks hybrides Data + Business Intelligence pour un impact scalable."
},en:{
"nav.projects":"Modules","nav.skills":"Skills","nav.certs":"Certifications","nav.contact":"Contact",
"portal.kicker":"ORBITAL COGNITIVE STATION","portal.sub":"Orbital research center dedicated to Artificial Intelligence and Data Science applied to Business","portal.cta":"[ CLICK TO ENTER ]","portal.b1":"Research Nodes",
"transition.1":"Biometric scan in progress...","transition.2":"Access granted","transition.3":"Opening cognitive core",
"cabin.prompt":"Click to activate cognitive scan","corridor.left":"Restricted Access","corridor.right":"Module Offline",
"globe.label":"CENTRAL COGNITIVE CORE",
"projects.kicker":"RESEARCH MODULES","projects.title":"Cognitive station archives","projects.desc":"Each module represents a real, documented and operational project.",
"skills.kicker":"COGNITIVE CONSOLE","skills.title":"Skill Matrix — Competency Map",
"certs.kicker":"ACCREDITATIONS","certs.title":"Certifications, Degrees & Awards",
"contact.kicker":"COMMUNICATION CHANNEL","contact.title":"Ready to collaborate on Data & AI projects","contact.cvTitle":"Curriculum Vitae",
"footer.text":"Built with passion for Data, AI and Business",
"bot.status":"local base","bot.chipProjects":"Projects","bot.chipSkills":"Skills","bot.chipContact":"Contact","bot.placeholder":"Ask about my profile...","bot.send":"Send",
"bot.welcome":"Welcome to KCSS. Ask about my projects, skills or background.",
"bot.projects":"6 modules: Mirakl Nexus (agentic AI), PayFit Content Engine (AI SEO), Safran CMMS (industry), TodoMaking (Dust agent), Olist Dashboard (BI Tableau), NBA Analytics (Python scraping).",
"bot.skills":"Skills in AI/agentic (Dust, n8n, Make), Data (Python, SQL, Power BI, Tableau), Dev (HTML/CSS/JS, GitHub), Methods (PMO, FMEA, 5S).",
"bot.contact":"Email: jkinvi@eugeniaschool.com | LinkedIn: linkedin.com/in/jahdiel-k | GitHub: github.com/ycoj2309",
"bot.default":"I don't have that specific info. Ask me about projects, skills or contact.",
"filter.all":"All","filter.ai":"AI","filter.data":"Data","filter.business":"Business","filter.industry":"Industry",
"card.open":"Explore","card.github":"GitHub",
"modal.context":"Context","modal.objective":"Objective","modal.result":"Results","modal.stack":"Stack","modal.links":"Links",
"profile.scan":"[Holographic Scan Active]","profile.identity":"IDENTITY","profile.role":"ROLE","profile.org":"ORGANIZATION","profile.edu":"EDUCATION","profile.status":"STATUS",
"profile.roleVal":"Data Analyst & Project Coordinator","profile.orgVal":"PMU — Commercial Network Development","profile.eduVal":"Eugenia School — MSc AI Applied to Business","profile.statusVal":"Active Cognitive Node — Kinvi Cognitive Space Station",
"profile.summary":"Specialized in data-driven decision systems and AI applied to business operations. Currently contributing to PMU's commercial network optimization and analytics. Focused on building hybrid Data + Business intelligence frameworks for scalable impact."
}};

const PROJECTS=[
{id:"mirakl",filter:"ai",num:"01",status:{fr:"Completed · Vainqueur UC2",en:"Completed · UC2 Winner"},
image:"6 Projets/HACKATHON MIRAKL/Gemini_Generated_Image_pp22mspp22mspp22.png",
title:{fr:"Mirakl Nexus — Sales Acceleration Engine",en:"Mirakl Nexus — Sales Acceleration Engine"},
subtitle:{fr:"Hackathon UC2 · Sourcing, scoring & emails IA",en:"UC2 Hackathon · Sourcing, scoring & AI emails"},
context:{fr:"Cockpit B2B pour Mirakl Connect : transformer le sourcing marketplace en leads qualifiés et messages personnalisés.",en:"B2B cockpit for Mirakl Connect: turn marketplace sourcing into qualified leads and personalised messages."},
objective:{fr:"Automatiser l'analyse, la priorisation, la rédaction et la traçabilité pour accélérer le travail BDR.",en:"Automate analysis, prioritisation, writing and traceability to accelerate BDR work."},
result:{fr:"707 prospects/jour, 80% de temps BDR économisé, 100% de personnalisation, vainqueur Best BDR Outreach Solution.",en:"707 prospects/day, 80% BDR time saved, 100% personalisation, winner Best BDR Outreach Solution."},
metrics:["707 prospects/jour","80% temps gagné","×14 volume","<40€/mois"],
stack:["Next.js","n8n","Supabase","GPT-4o","Dust","Apollo","Brevo"],
links:[{label:"GitHub",href:LINKS.miraklGh1},{label:"Loom Demo",href:LINKS.miraklLoom1},{label:"Vercel",href:LINKS.miraklVercel},{label:"LinkedIn",href:LINKS.linkedinPost},{label:"PDF Engine",href:"6 Projets/HACKATHON MIRAKL/AI-Powered Sales Acceleration Engine.pdf"}]},

{id:"payfit",filter:"ai",num:"02",status:{fr:"Completed · Vainqueur",en:"Completed · Winner"},
image:"6 Projets/HACKATHON PAYFIT/Photos/Image 1.webp",
title:{fr:"PayFit Content Engine — Pipeline IA 9 agents",en:"PayFit Content Engine — 9-agent AI Pipeline"},
subtitle:{fr:"Vainqueur Hackathon SEO for PayFit",en:"Winner of SEO for PayFit Hackathon"},
context:{fr:"Pipeline éditorial automatisé pour sujets RH/paie TPE-PME, depuis la détection des signaux jusqu'au maillage.",en:"Automated editorial pipeline for HR/payroll SMB topics, from signal detection to linking."},
objective:{fr:"Orchestrer 9 agents Dust : Content Engine, analyse concurrentielle, rédaction, contrôle légal, EEAT, backlinks et GEO.",en:"Orchestrate 9 Dust agents: Content Engine, competitive analysis, writing, legal checking, EEAT, backlinks and GEO."},
result:{fr:"9 agents Dust, 20 sujets/jour scannés, 1148 articles analysés, validation légale Légifrance, certificat vainqueur.",en:"9 Dust agents, 20 topics/day scanned, 1148 articles analysed, Legifrance legal validation, winner certificate."},
metrics:["9 agents","20 sujets/jour","1148 articles","60s backlinks"],
stack:["Dust","Lovable","Google Apps Script","Apify","SEMrush","Légifrance API"],
links:[{label:"Site Live",href:LINKS.payfitLive},{label:"Certificat",href:"6 Projets/HACKATHON PAYFIT/Certificat_Hackathon_PayFit (1).pdf"},{label:"Notion",href:LINKS.notion}]},

{id:"safran",filter:"industry",num:"03",status:{fr:"Completed Research Node",en:"Completed Research Node"},
image:"Compétences images/carl source.png",
title:{fr:"Safran — Méthodes industrielles & GMAO",en:"Safran — Industrial Methods & CMMS"},
subtitle:{fr:"Stage industriel 7 mois · SolidWorks · CARL Source",en:"7-month industrial internship · SolidWorks · CARL Source"},
context:{fr:"Projet issu d'une expérience industrielle de 7 mois chez Safran, avec structuration GMAO et pilotage PMO.",en:"Project from a 7-month industrial experience at Safran, with CMMS structuring and PMO leadership."},
objective:{fr:"Structurer +2000 organes, déployer CARL Source, piloter AMDEC/5S et produire des reportings executive.",en:"Structure 2000+ components, deploy CARL Source, lead FMEA/5S and produce executive reports."},
result:{fr:"+2000 organes structurés, 95% actions correctives réussies, 5S de 0.16 à 3/5, reporting executive.",en:"2000+ components structured, 95% corrective actions successful, 5S from 0.16 to 3/5, executive reporting."},
metrics:["+2000 organes","95% corrections","5S: 0.16→3/5","7 mois"],
stack:["CARL Source","OptiMaint","Excel VBA","SolidWorks","AMDEC","RACI","5S"],
links:[{label:"Soutenance PDF",href:"6 Projets/SAFRAN GMAO/Présentation soutenance .pdf"},{label:"SolidWorks PDF",href:"6 Projets/Autres projets/Présentation Projet Solidworks (version finale).pdf"}]},

{id:"todo",filter:"business",num:"04",status:{fr:"Operational Node",en:"Operational Node"},
image:"Compétences images/dust_tt_logo.jpeg",
title:{fr:"TodoMaking — Documents vers tâches IA",en:"TodoMaking — Documents to AI Tasks"},
subtitle:{fr:"Agent Dust · NLP · Priorisation automatique",en:"Dust Agent · NLP · Auto-prioritisation"},
context:{fr:"Assistant capable de lire emails, comptes-rendus et rapports pour extraire les actions à réaliser.",en:"Assistant able to read emails, minutes and reports to extract actionable tasks."},
objective:{fr:"Transformer du texte brut en tableau de tâches priorisées sans hallucination, avec responsable et deadline.",en:"Turn raw text into a prioritised task table without hallucination, with owner and deadline."},
result:{fr:"-2h30 par semaine, 100% de capture des tâches, 0 hallucination et +40% de productivité.",en:"-2h30 per week, 100% task capture, zero hallucination and +40% productivity."},
metrics:["-2h30/semaine","100% capture","0 hallucination","+40% productivité"],
stack:["Dust","NLP","Prompt Engineering","React"],
links:[{label:"Présentation",href:"6 Projets/Todomaking/Presentation_Todomaking.pdf"},{label:"Gantt",href:"6 Projets/Todomaking/MiniGantt.pdf"}]},

{id:"olist",filter:"data",num:"05",status:{fr:"Completed Research Node",en:"Completed Research Node"},
image:"Compétences images/image tableau logo.jpeg",
title:{fr:"Olist Dashboard — E-commerce Brésil",en:"Olist Dashboard — Brazilian E-commerce"},
subtitle:{fr:"Business Case Tableau Desktop · 99k commandes",en:"Tableau Desktop Business Case · 99k orders"},
context:{fr:"Dashboard décisionnel sur le marketplace Olist de mars 2017 à juin 2018.",en:"Decision dashboard on the Olist marketplace from March 2017 to June 2018."},
objective:{fr:"Donner une lecture claire à un public non technique : opérations, carte par État et évolution mensuelle.",en:"Give a clear view to non-technical stakeholders: operations, state map and monthly evolution."},
result:{fr:"99 441 commandes analysées, 27 États, 8 statuts opérationnels, publication Tableau.",en:"99,441 orders analysed, 27 states, 8 operational statuses, Tableau publication."},
metrics:["99 441 commandes","27 États","8 statuts","15 mois"],
stack:["Tableau Desktop","SQL","Geo Analysis","Time Series"],
links:[{label:"Tableau Public",href:LINKS.olistTableau},{label:"Business Case PDF",href:"6 Projets/Olist Dashboard/Assets/Business_Case_Olist.pdf"}]},

{id:"nba",filter:"data",num:"06",status:{fr:"Completed Research Node",en:"Completed Research Node"},
image:"6 Projets/NBA Scraping/Images/01_salary_vs_points.png",
title:{fr:"NBA Analytics — Salaires vs Performance",en:"NBA Analytics — Salary vs Performance"},
subtitle:{fr:"Scraping multi-sources · Statistiques · Régression",en:"Multi-source scraping · Statistics · Regression"},
context:{fr:"Analyse de la saison NBA 2024-25 avec 508 joueurs pour comprendre si le salaire explique la performance.",en:"Analysis of the 2024-25 NBA season with 508 players to understand whether salary explains performance."},
objective:{fr:"Construire un dataset fiable, fusionner salaires et stats avancées, puis tester des hypothèses mesurables.",en:"Build a reliable dataset, merge salaries and advanced stats, then test measurable hypotheses."},
result:{fr:"Pearson r=0.815, R²=64.3%, +340k$ par point supplémentaire, 13 best deals identifiés.",en:"Pearson r=0.815, R²=64.3%, +$340k per extra point, 13 best deals identified."},
metrics:["508 joueurs","r=0.815","R² 64.3%","13 best deals"],
stack:["Python","BeautifulSoup","Selenium","Pandas","SciPy","Matplotlib"],
links:[{label:"GitHub",href:LINKS.nbaRepo}]}
];

const SKILLS=[
{title:{fr:"IA & Agentique",en:"AI & Agentic"},ring:"inner",
desc:{fr:"Agents, prompts, orchestration et intégration d'APIs IA.",en:"Agents, prompts, orchestration and AI API integration."},
logos:["dust_tt_logo.jpeg","make-ai.webp","Google-Apps-Script-1.webp"],
tags:["Dust","n8n","OpenAI API","Make","Prompt Engineering","AI Agents"]},
{title:{fr:"Data & BI",en:"Data & BI"},ring:"mid",
desc:{fr:"Collecte, nettoyage, modélisation statistique et visualisation.",en:"Collection, cleaning, statistical modelling and visualisation."},
logos:["Python-logo-notext.svg.png","New_Power_BI_Logo.svg.png","image tableau logo.jpeg","Microsoft_Office_Excel_(2025–present).svg.png"],
tags:["Python","SQL","Tableau","Power BI","Pandas","Excel VBA","Web Scraping"]},
{title:{fr:"Dev & Outils",en:"Dev & Tools"},ring:"outer",
desc:{fr:"Web, prototypage, versioning et déploiement.",en:"Web, prototyping, versioning and deployment."},
logos:["Visual_Studio_Code_1.35_icon.svg.png","Gsheets.png"],
tags:["HTML/CSS/JS","GitHub Pages","Git","React","Linux"]},
{title:{fr:"Méthodes & Industrie",en:"Methods & Industry"},ring:"cognitive",
desc:{fr:"Pilotage projet, reporting, coordination et restitution.",en:"Project leadership, reporting, coordination and presentation."},
logos:["carl source.png","5S.jpg","solidworks.png"],
tags:["PMO","AMDEC/FMEA","RACI","5S","CARL Source","SolidWorks"]}
];

const CERTS=[
{title:{fr:"🏆 Vainqueur Hackathon SEO for PayFit",en:"🏆 Winner SEO for PayFit Hackathon"},meta:{fr:"PayFit × Make × Dust × Eugenia — Mars 2026",en:"PayFit × Make × Dust × Eugenia — March 2026"},href:"6 Projets/HACKATHON PAYFIT/Certificat_Hackathon_PayFit (1).pdf"},
{title:{fr:"🏆 Vainqueur UC2 Hackathon Mirakl",en:"🏆 Winner UC2 Mirakl Hackathon"},meta:{fr:"Mirakl × Eugenia × n8n × Dust — Avril 2026",en:"Mirakl × Eugenia × n8n × Dust — April 2026"},href:"6 Projets/HACKATHON MIRAKL/AI-Powered Sales Acceleration Engine.pdf"},
{title:{fr:"🎓 MSc AI Applied to Business",en:"🎓 MSc AI Applied to Business"},meta:{fr:"Eugenia School — 2026-2028 (en cours)",en:"Eugenia School — 2026-2028 (ongoing)"},href:""},
{title:{fr:"🎓 Licence SPI Maintenance Industrielle",en:"🎓 BSc Industrial Maintenance Engineering"},meta:{fr:"UPEC Paris-Est Créteil — 2022-2025",en:"UPEC Paris-Est Créteil — 2022-2025"},href:""}
];
